# Generated by Django 5.2.4 on 2025-10-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
    ]
