# Generated by Django 5.2.4 on 2025-10-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_role_options'),
        ('ecommerce', '0003_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_man_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(blank=True, db_column='delivery_man_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='adminpanel.user'),
        ),
    ]
