# Generated by Django 5.2.4 on 2025-09-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
    ]
