# Generated by Django 5.2.4 on 2025-10-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
    ]
